### ISSUE TITLE
Move "Download Model" logic out of Dockerfile

### ISSUE THREAD

**Issue by dennyabrain** [tattle-made/OGBV#119]
https://github.com/tattle-made/OGBV/blob/4091118d8dee097604f7a95cdebb0a12b2cd5984/FastAPI%20-%20OGBV/Dockerfile#L7-L9

Downloading the model and packaging it into the dockerfile leads to a very large docker image/container. We should move the download logic into the code itself so that the container can be light and it can download to module into an attached docker/kubernetes volume before running.

**Comment by dennyabrain** [comment]
- [ ] identify and document the the ml model is downloaded and saved
- [ ] use docker volumes to save the model on host machine as opposed to inside the container
- [ ] do a comparison before/after of docker image size and document it
- [ ] push this new image to dockerhub
- [ ] deploy new model and verify

**Comment by dennyabrain** [comment]
@Bhargav-Dave helped identify two critical locations
1. The location where ML model is downloaded (/app/assets)
2. The location where pytorch binary is downloaded (/root/.cache/huggingface/transformers)

To test out caching of hugging face, first create a directory on your local machine called `ogbv-ml-rest-data` and keep its full absolute path handy. for me it was `/home/tattle/Playground/ogbv-ml-rest-data/`
then run the following
```
docker run 
   -v /home/tattle/Playground/ogbv-ml-rest-data/cache:/root/.cache/huggingface/transformers 
   ogbv-ml-rest
```

This will download all pytorch and hugging face related data in your ogbv-ml-rest-data directory. you can verify it too.
the first time you run this docker command, you will see the 1gb pytorch_bin being downloaded but the subsequent times the container startup would be within seconds!!!

Ideally to close out this issue we want to be able to run the following command : 
```
docker run 
    -v /home/tattle/Playground/ogbv-ml-rest-data/assets:/app/assets 
    -v /home/tattle/Playground/ogbv-ml-rest-data/cache:/root/.cache/huggingface/transformers 
    ogbv-ml-rest
```

This will ensure that even the ML model is not downloaded everytime. Right now since the model is part of the docker image, running this command will crash because the code will expect to find model_dict.bin inside your ogbv-ml-rest/assets directory.
So lets move the download model logic out of the Dockerfile and into the python code.

**Comment by dennyabrain** [comment]
Adding this visual for references

![ogbv-ml-rest-docker-size-issue](https://user-images.githubusercontent.com/1415361/188084656-0bbd9402-6cda-4570-96cc-072a2a719e9a.png)

**Comment by Bhargav-Dave** [comment]
Currently, the download model logic has been removed from the Dockerfile and the logic is added to the commands that are run when the docker container is run. Thus the downloaded model is not a part of the image but the container as depicted by @dennyabrain in his infographic.

Before the use of containers, the time to download the model was around **26 minutes** which included the time to download all the python requirements and two large files, ergo building and running the container. After the volumes are added, the time is reduced to around **9.5 minutes**. 

Downloading the python requirements takes around 9 minutes for me so effectively, the download time would be 17 minutes which is completely cut down. So the time required to run the container is reduced from 17 minutes to a matter of 20-30 seconds!

This also effectively saves 2.247 GB of data everytime as compared to the earlier approach. You only have to download this data once and as long as the volumes are saved, it would save the time and data everytime you run the container afterwards.
