### ISSUE TITLE
Deploy the dockerized API server to our K8 cluster

### ISSUE THREAD

**Issue by dennyabrain** [tattle-made/OGBV#126]
- [x] #128
- [x] #142

**Comment by dennyabrain** [comment]
@whymath we are good to go on this task now :)

@Bhargav-Dave has pushed the ml server image to https://hub.docker.com/repository/docker/tattletech/ogbv-ml-rest
he's also configured the repo in a way that any changes to the ogbv-ml-rest directory will trigger a push of a new image to dockerhub. 
Do you want to take a stab at deploying this on kubernetes and ping us with any doubts?

One thing i foresee is that this image is very big in size ~1gb and as of now thats part of the docker image itself. having the ml model be part of the docker image is a technical debt which we wish to address at some point but if you can work with it, i can defer doing that for some time. lmk

**Comment by whymath** [comment]
@dennyabrain the ogbv-ml-rest image has been deployed to our Prod cluster and Dev clusters. Image size isn't a problem and can be deferred for the short- and medium-term.

I've also added auto-deploy scripts on both of them, so you can go ahead and convert the "Add github action to automatically deploy new image to k8" action item to an issue and take that ahead (will share the snippet separately).
