### ISSUE TITLE
Add github action to automatically deploy new image to k8

### ISSUE THREAD

**Issue by dennyabrain** [tattle-made/OGBV#142]

**Comment by dennyabrain** [comment]
@whymath you mentioned you've created an auto deploy script. 
just want you to take a look at this github action I've been using 
https://github.com/tattle-made/OGBV/blob/6f8e36241b4eda7d8c3ad2da754157813d2e8192/.github/workflows/deploy-prod.yml#L57-L67

I've added the kubeconfig file as a secret on github which allows me to take actions on the cluster directly from actions. One limitation of the action right now is that since our deployment files are not part of the repo, we cant deploy the very first time via this action. that has to be manual. once the necessary deployment, service, ingress etc are in place, this action does great for automatic deployment.

**Comment by whymath** [comment]
@dennyabrain yup this should work
