### ISSUE TITLE
Incorrect background color on Uli website pages

### ISSUE THREAD

**Issue by tarunima** [tattle-made/OGBV#167]
If you go to a sub page on Uli website directly through  a URL, say https://uli.tattle.co.in/blog/, the background color is different from the defined Uli color.  If you click on any of the tabs, those too have pale white background. but when you refresh the color goes back to the Uli background color.

**Comment by Bhargav-Dave** [comment]
This has been resolved in the following: https://github.com/tattle-made/OGBV/pull/220

The issue had to do with the webpage referring to the relative path of the colour rather than the absolute path.
