### ISSUE TITLE
Make slur replacement case insensitive

### ISSUE THREAD

**Issue by tarunima** [tattle-made/OGBV#170]
Currently slur replacement is case sensitive. Simple fix is to ensure all slurs are in lower case and convert tweet to lower case before doing a string compare.

**Comment by dennyabrain** [comment]
Current Implementation
https://github.com/tattle-made/OGBV/blob/main/browser-extension/plugin/src/slur-replace.js#L6-L19

Can the regex query be modified to make this case insensitive.

That is if the word "cat" is added to the slurlist, it should replace "cat", "Cat" or "cAT" with the mask character ▓

**Comment by Bhargav-Dave** [comment]
Currently, owing to the 'i' flag being present in the following line:

`var expression = new RegExp(`(?:${slurList})`, 'gi');`

the slur replacement in English is case insensitive and this has been verified through observation by multiple members. Hence, closing the issue, will reopen if counterexamples arise
