### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by tarunima** [tattle-made/OGBV#194]
**Website Fixes**
List of the updates on the website

- [x] Add the explainer videos on the user guide page
- [x] Split FAQs from User Guide and create a new page
- [x] Add Twitter Handle for Uli on home page
- [x] In footer, change the text: 'Uli is now available on Chrome..' to 'Uli is now available for installation.'
- [x] In footer, 'Learn How to Use' should link to the user guide. 
- [ ] When language is selected from drop-down, the language of the user guide should also change.

**Comment by dennyabrain** [comment]
@tarunima closing this issue. the language issue is slightly complicated. so breaking it into a new issue

**Comment by dennyabrain** [comment]
Actually its already here - https://github.com/tattle-made/OGBV/issues/162
