### ISSUE TITLE
Add faq page in hindi and tamil

### ISSUE THREAD

**Issue by dennyabrain** [tattle-made/OGBV#195]
The website is lacking a faq page for hindi and tamil

Translations can be found here
Tamil Text : https://docs.google.com/document/d/1sKx9pRJvX_YEHuYHfi9uoFVM6qQQjFXl/edit?usp=share_link&ouid=115793107014924574949&rtpof=true&sd=true
Hindi Text : https://docs.google.com/document/d/1CQj0-G6NyJxoVhmwyRgehiiTBDqJ3wmZQDiAoUfZh8c/edit?usp=sharing

send @tarunima or @dennyabrain your email if you'd like  access

**Comment by Bhargav-Dave** [comment]
This has been resolved in: https://github.com/tattle-made/OGBV/pull/198
