### ISSUE TITLE
Dimension values should be stored in english in the db

### ISSUE THREAD

**Issue by dennyabrain** [tattle-made/OGBV#23]
@tarunima I just realized that I have been storing dimension values as string in the db. this string is the string thats returned by the UI. which is usually fine but I just realized that for the multilingual setup, if a user choses "religion" as the option for dimension, it would get stored as "religion", "धर्म" or "மதம்", depending on the language of the user.

I have two proposed solutions.
1. Fix it on the db level so that regardless of language, the db stores a consistent value.
2. We just deal with it on the sql level. anytime we need to group annotations by dimension value we'll have to use a bunch of OR commands.

**Comment by tarunima** [comment]
@dennyabrain does this still need to be resolved?

**Comment by dennyabrain** [comment]
I guess if we are just using binary yes, no fields for now, this is not relevant anymore. So ok to close.
