### ISSUE TITLE
XPI file cannot be created using web-ext because of extension size

### ISSUE THREAD

**Issue by Bhargav-Dave** [tattle-made/OGBV#233]
`web-ext` is a framework useful in order to pack the extension into an xpi file. An xpi file is used to load the extension into firefox for testing and also submitting to the firefox store. However firefox does not allow packing files that are larger than 4 MB. 

Refer the following: https://discourse.mozilla.org/t/firefox-web-extension-background-script-to-bundle-or-not-to-bundle/82805

After adding the feedback feature, the code of the plugin has exceeded 4MB and we assume that the size of the code will only increase as we add more features. The proposed solution is to bundle the code and investigation and work needs to be done on the same.

**Comment by Bhargav-Dave** [comment]
Because of the above issue, no new updates or features have been added to Firefox and thus some of the new functionality is missing or breaking in Firefox currently. The features which are working and which are not have been documented in the readme.

**Comment by dennyabrain** [comment]
@Bhargav-Dave can you please put the command thats failing along with the error logs here?

**Comment by dennyabrain** [comment]
I am able to run the web-ext sign command and create an .xpi file and load on firefox.

**Comment by duggalsu** [comment]
The new firefox extension has been released successfully. Closing this issue.
