### ISSUE TITLE
Some tweets are longer than 500

### ISSUE THREAD

**Issue by dennyabrain** [tattle-made/OGBV#25]
I found a tweet that seems to be longer than 500 characters.
I thought twitter had a tweet length limit of 480 characters. I'll have to reconfigure the database to support > 500 characters. which is not a problem, but i'd like to know what is the issue here. does twitter support longer tweets now and if yes, is there a character limit?

**Comment by Siddhant-K-code** [comment]
Can You Please Send the Tweet URL, so we can diagnose it!

**Comment by dennyabrain** [comment]
The tweet id i see in the DB is 1463520912280408070 and URL maps to [this](https://twitter.com/Hindu977/status/1463520912280408070)

As I am looking at this i realize that the tweet itself is <280 chars but because the user is "Replying to 
@DanielBSingh1 @Aatma_the_soull and 19 others", our scraper expands the "19 others" to all usernames and that gets counted in the tweet length. 

We'll probably need to modify the scraper logic on this.

I'll close the issue. thank you for asking this, made me look closely and find the solution :D
