### ISSUE TITLE
Browser Does not remember username and password

### ISSUE THREAD

**Issue by dennyabrain** [tattle-made/OGBV#31]
Ambika reported that if she saves her username and login on firefox and tries to relogin using that credentials, it doesnt work. she has to relogin everytime.

**Comment by dennyabrain** [comment]
so, first of all I am not sure if its a browser bug or react bug, since this codebase is not well documented, i was hoping if someone could do some research on it and revert with how this can be fixed.
The UI code for the login page is here - https://github.com/tattle-made/OGBV/blob/main/annotators/annotation-ui/src/pages/login.jsx
we use [Grommet](https://v2.grommet.io/components) for ui components.

**Comment by dennyabrain** [comment]
fyi, the code for the annotation UI is limited to the [annotators](https://github.com/tattle-made/OGBV/tree/main/annotators) folder of this repo. 
in the absence of documentation, setting up the backend without my assistance would require understanding of nodejs/express AND sequelize ORM so I am hoping this task can be fixed purely by making changes on the UI layer.

**Comment by dennyabrain** [comment]
and if that is not possible, then happy to schedule a call to go over setting this up locally and document it in the process.

**Comment by Siddhant-K-code** [comment]
Related to Files:

- https://github.com/tattle-made/OGBV/blob/6a41e6f094a05540536a798bcbfcd8961d8e831f/annotators/annotation-ui/src/pages/login.jsx#L46
    - https://github.com/tattle-made/OGBV/blob/6a41e6f094a05540536a798bcbfcd8961d8e831f/annotators/annotation-ui/src/controller/login.js#L16
    - https://github.com/tattle-made/OGBV/blob/6a41e6f094a05540536a798bcbfcd8961d8e831f/annotators/annotation-ui/src/repository/user.js#L12

**Comment by dennyabrain** [comment]
Quick Instructions to get the project running
1. run `docker-compose up` to bring up the sql database and a database GUI
2. cd into annotators/backend/sequelize and run `npx sequelize-cli db:migrate` - this will create the tables in db
3. run `npx sequelize-cli db:seed --seed 20211115172651-beta-test` - this will run the script located [here](https://github.com/tattle-made/OGBV/blob/main/annotators/backend/sequelize/seeders/20211115172651-beta-test.js) and insert users named tarunima, arnav etc. You will have to check the db to see their password. which is stored in plain text for now.

**Comment by dennyabrain** [comment]
If this is your first time using sequelize, i suggest spending sometime reading its documentation and specifically [this page](https://sequelize.org/v6/manual/migrations.html) to familiarise yourself with migrations and seeding

**Comment by dennyabrain** [comment]
@Siddhant-K-code could you also look into what are the best practices to developing login form. From a cursory research that I did, it seems like if we implement our login section as part of an html form and add the attribute `autocomplete` to the username and password field, the browser should take care of the rest.
ref : https://www.w3schools.com/TagS/att_input_autocomplete.asp

can you investigate if
1. there's more to it
2. if this fixes this bug

**Comment by tarunima** [comment]
@dennyabrain can you confirm that this can be closed?

**Comment by dennyabrain** [comment]
Not yet. Its not fixed yet and we dont have a solution so far

**Comment by dennyabrain** [comment]
Not relevant anymore
