### ISSUE TITLE
regex capture group not working with non english text

### ISSUE THREAD

**Issue by dennyabrain** [tattle-made/OGBV#35]
# Task Description
This task is part of our slur replacement project. The basic requirement of the function is to take an input string and hide the problematic slurs within it.

# Current Approach
I am pasting a simpler reproduction of my solution to demonstrate how things should work.
```javascript
let input = "I have a cat, dog and a goat";

function hideSlurs(text) {
  return text.replace(/\b(?:cat|dog|goat)\b/gi, "----");
}

let output = hideSlurs(input);
console.log(output);
``` 
The output in this case becomes "I have a ----, ---- and a ----". 
As you can see, the word cat, dog, goat are replaced by '----'. 
# Problem
The `hideSlurs` function fails with non english words.
```javascript
let input = "मेरे पास एक बिल्ली, कुत्ता और एक बकरी है";

function hideSlurs(text) {
  return text.replace(/\b(?:बिल्ली|कुत्ता|बकरी)\b/gi, "----");
}

let output = hideSlurs(input);
console.log(output);
```
In this case the output is the same as the input. I get similar results trying with Tamil text.

How can we modify the hideSlurs function to make it work with non latin characters. 

Note : although the project uses javascript and the code here is javascript too, if you can make it work in any language, that would be useful for us in debugging this too.

**Comment by d80ep08th** [comment]
Regex categorizes Words, Digits, Whitespaces and Special Characters . I cant tell about other non-english words but when it comes to hindi words, regex categorizes hindi characters as special characters. That is the reason why the regex : `/\b(?:बिल्ली|कुत्ता|बकरी)\b/g`
is wrong. Since `\b` is used to encapsulate a word boundary. To encapsulate a string made of special characters, regex uses `\B` for non-word boundary. Hence , the solution : `/\B(?:बिल्ली|कुत्ता|बकरी)\B/g` .
For that matter, this solution works if we just drop `\b`  : `/(?:बिल्ली|कुत्ता|बकरी)/g`

**Comment by Siddhant-K-code** [comment]
^ By Above Discussion, Possible Solution: 

```javascript

let input = "मेरे पास एक बिल्ली, कुत्ता और एक बकरी है";

function hideSlurs(text) {
  return text.replace(/(?:बिल्ली|कुत्ता|बकरी)/gi, "----");
}

let output = hideSlurs(input);
console.log(output);

```

it will give output as:

```console
मेरे पास एक ----, ---- और एक ---- है
```

thanks @d80ep08th 🙏🏼

**Comment by dennyabrain** [comment]
@Siddhant-K-code if you've already setup a local test of this, could you check if this input can pass through the function with all keywords replaced - "मेरे पास एक बिल्ली और एक goat है". 
I want to figure out what changes should be made in the regex expression to support strings with text in it in multiple languages.

**Comment by Siddhant-K-code** [comment]
A Better Solution:

```javascript

let input = "मेरे पास एक बिल्ली, कुत्ता और एक बकरी and cat है";

function hideSlurs(text) {
  return text.replace(/(?:बिल्ली|कुत्ता|बकरी|cat)/gi, "----");
}

let output = hideSlurs(input);
console.log(output);

```

```terminal
मेरे पास एक ----, ---- और एक ---- and ---- है
```

**Comment by dennyabrain** [comment]
oh great. thank you both of you. I'll link the commit to this issue when I am done.

**Comment by dennyabrain** [comment]
I have some concerns about pushing our slur list on github and hence opening it up. So we're still figuring out with the rest of the team on this project how to tackle this issue. Will notify what its decided.

**Comment by dennyabrain** [comment]
Hi @d80ep08th , I have discovered a test case that does not provide the required output. if you run this function for the input `मेरे पास एक बिल्ली, कुत्ता और एक बकरी ,cat and cathod ray tube hain है`, the output it produces is `मेरे पास एक ----, ---- और एक ---- ,---- and ----hod ray tube hain है`
As you see the word cat in cathode was also blurred out. So i am guessing this has got to do with us removing the boundary condition from regex. I was thinking maybe one quickfix is to just add space around the keyword in the text.replace function itself?   
Any other thoughts?

Ignore the convoluted input sentence here but lets try to make this test case work.

```
let input =
  "मेरे पास एक बिल्ली, कुत्ता और एक बकरी ,cat and cathod ray tube hain है. हवाला";

function hideSlurs(text) {
  return text.replace(/(?:बिल्ली|कुत्ता|बकरी|cat|हवा)/gi, "----");
}

let output = hideSlurs(input);
console.log(output);
```
current output : `मेरे पास एक ----, ---- और एक ---- ,---- and ----hod ray tube hain है. ----ला`
expected output `मेरे पास एक ----, ---- और एक ---- ,---- and -cathod ray tube hain है. हवाला`

**Comment by d80ep08th** [comment]
The regex expression ` /(?:बिल्ली|कुत्ता|बकरी|cat|हवा)/ ` will look for those patters everywhere, even inside a string.

To solve this issue , we have to let the regex know that the pattern we are searching is supposed to be a string in itself .

To do that we use 
==> `^`  ==> indicates start of a string
and 
==> `$` ==> indicates end of a string 

With respect to that, my proposed solution would be to replace the regex  ` /(?:बिल्ली|कुत्ता|बकरी|cat|हवा)/ ` with the following : 
`/^(?:बिल्ली|कुत्ता|बकरी|cat|हवा)$/`

**Comment by mlkorra** [comment]
@d80ep08th Is the solution working for you? I have tried on my end but the issue still persists, also it isn't removing the slurs

Code used : 

```
let input =
  "मेरे पास एक बिल्ली, कुत्ता और एक बकरी ,cat and cathode ray tube hain है. हवाला";

function hideSlurs(text) {
  return text.replace(/^(?:बिल्ली|कुत्ता|बकरी|cat|हवा)$/, "----");
}

let output = hideSlurs(input);
console.log(output);
```

Output -

```
मेरे पास एक बिल्ली, कुत्ता और एक बकरी ,cat and cathode ray tube hain है. हवाला

```

I am running it on an online [compiler](https://onecompiler.com/javascript/3xs68ktg9)

**Comment by d80ep08th** [comment]
I am trying it in my node compiler and it aint working there . Its taking the whole input as one string and thats why my proposed solution is not working, I am working on an alternative right now.

**Comment by mlkorra** [comment]
On python 


```
pattern = r'बिल्ली|कुत्ता|बकरी|cat|हवा'

hin_input = "मेरे पास एक बिल्ली, कुत्ता और एक बकरी ,cat and cathode ray tube hain है. हवाला"

output_string = ""

for token in hin_input.split(' '):
    
    
    match = re.fullmatch(pattern,token.strip('.,'))
    
    if match:
        
        match = match.group(0)
        
        replace_token = '----' + token.strip(str(match))
        output_string += ' ' + replace_token
    
    else:
        
        output_string += ' ' + token
    
print(new_string)

Output -
 मेरे पास एक ----, ---- और एक ---- ----, and cathode ray tube hain है. हवाला


```
Some inconsistency with punctuations

**Comment by mlkorra** [comment]
@dennyabrain closing the issue for now

**Comment by dennyabrain** [comment]
Thanks for the help. I took inspiration from your approaches to implement a quickfix in my existing setup.

The earlier regex query was capturing matching slurs and running a function for each match. In that function we determine what the preceding and next character is. If they are not spaces or punctuation, then we don't add the mask.

Relevant Snippet 
https://github.com/tattle-made/OGBV/blob/309f5429e58ef26574cbd4536d6d671e2993bf22/chrome-plugin/react/slur-replace.js#L6-L18
