### ISSUE TITLE
Add npm audit pre-commit hook

### ISSUE THREAD

**Issue by duggalsu** [tattle-made/OGBV#46]
This is essential with multiple code contributors. For example, the current `chrome-plugin/` code has a `package-lock.json` with `lockfileVersion` 2. 

`npm install` with an older node version may give the following warning - 

```
read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
```

The command may finish successfully but result in installing node-modules with security vulnerabilities and modifying `package-lock.json` with a downgraded `lockfileVersion`. 

This will require fixing dependency issues as flagged by `npm audit`

See -
https://docs.npmjs.com/cli/v8/commands/npm-audit

```
	By default, the audit command will exit with a non-zero code if any vulnerability is found. It may be useful in CI environments to include the --audit-level parameter to specify the minimum vulnerability level that will cause the command to fail. This option does not filter the report output, it simply changes the command's failure threshold.
```

**Comment by dennyabrain** [comment]
nice catch @duggalsu. if you make progress on this make a PR. its new learning for me too and i'd like to copy it across other JS projects too.
