### ISSUE TITLE
Incorporate ML model for tweet classification

### ISSUE THREAD

**Issue by dennyabrain** [tattle-made/OGBV#51]
- [ ] Containerize the app and deploy to Kubernetes
- [x] Expose the functionality of the ML Model via a REST API
- [ ] https://github.com/tattle-made/services-infrastructure/issues/8
- [ ] Incorporate classification of tweets on the UI

**Comment by dennyabrain** [comment]
@mahalakshmijinadoss, @mlkorra Can we work on providing a REST server with an ML model on it so that we can test it out on the high memory machines? Ideally we should have atleast a dummy version ready by March 25th. Let me know if anything is needed from our end to help in this.

**Comment by mlkorra** [comment]
### Instructions for running FASTAPI ogbv server
https://github.com/tattle-made/OGBV/issues/55#issuecomment-1067678274
