### ISSUE TITLE
Provide offline support for approximate slur replacement

### ISSUE THREAD

**Issue by dennyabrain** [tattle-made/OGBV#54]
@mlkorra has written python code that uses fuzzy search to detect approximate matches for slurs - https://github.com/tattle-made/OGBV/blob/main/slur-replacement/Slur%20Replacement%20-%20SCRIPT.ipynb

This code is in python and the way to integrate this functionality in our Chrome Plugin would be to expose this functionality via a REST API. This of course would add latency and network calls made from the extension.

I see a potential to incorporate this approximate slur replacement function into the extension code itself. This will make it so that the feature will be able to work without any internet.

The key to achieve this would be to use [WebAssembly](https://webassembly.org/)
Web assembly support is built into all modern browsers now. There are compilers that will compile languages like python, go, C, c++ to webassembly. Allowing web apps to rely not just on javascript but these other languages too.
This is a similar project for python - https://github.com/pyodide/pyodide

@mlkorra's code relies on python and 2 libraries - fuzzywuzzy, Levenstein. Levenstein's code is written in C. So I think theoretically it should be possible to compile his code to webassembly and bundle that with the chrome extension. The extension will communicate with the webassembly app to get the approximate slur replacement feature as opposed to a REST API hosted on cloud ([associated issue](https://github.com/tattle-made/OGBV/issues/55)).

**Comment by mlkorra** [comment]
@dennyabrain  [Levenstein](https://github.com/maxbachmann/Levenshtein) uses the same code base from [python-Levenstein](https://github.com/ztane/python-Levenshtein),but the latter is currently not being maintained

**Comment by dennyabrain** [comment]
i see. @mlkorra can you confirm for me if replacing Levenstien with python-levenstein changes the result?
Since this is the type of core library that does not require constant improvements, its possible that the unmaintained status is not a problem as long as the functionality is the same.

If we can use python-levenstein(which uses C and has wheels available for it), we might be able to compile it to web assembly and use in the browser easily.

**Comment by mlkorra** [comment]
@dennyabrain  Alright, will work on that and let you know.
