### ISSUE TITLE
Add support for approximate slur replacement via API calls

### ISSUE THREAD

**Issue by dennyabrain** [tattle-made/OGBV#55]
@mlkorra has written a REST API server to expose the approximate slur replacement. We'd like to deploy that to our kubernetes cluster and start using it in the extension.

### Missing Features : 
- [ ] #67
- [ ] modify the github action to deploy to k8
- [ ] Incorporate the API in chrome extension @dennyabrain

**Comment by dennyabrain** [comment]
@mlkorra Can you document the REST API server? Specifically, the steps to run the server and 1 (or more) test API request that we can make to check if the API is functioning correctly

**Comment by mlkorra** [comment]
@dennyabrain I have implemented FastAPI server for exposing the OGBV functionality ,I have to work on the REST API for slur replacement

**Comment by dennyabrain** [comment]
@mlkorra noted. 
So if i am understanding this correctly, you have done the REST API task for this - https://github.com/tattle-made/OGBV/issues/51, right? 

Regardless, Can you prioritize documenting the steps to run the FastAPI server  and pinging it before you move on to the rest api for slur replacement?
That ways @d80ep08th can parallelly work on deploying it and testing it.

**Comment by mlkorra** [comment]
@dennyabrain  Correct, sure will do that.

**Comment by dennyabrain** [comment]
great, when you are done link the documentation here and also on https://github.com/tattle-made/OGBV/issues/51. This way everyone involved will be in loop.

**Comment by mlkorra** [comment]
### Instructions for running FASTAPI ogbv server

- Install pyenv - [Ubuntu 18.04 Command 'pyenv' not found, did you mean:](https://stackoverflow.com/questions/62743132/ubuntu-18-04-command-pyenv-not-found-did-you-mean "Ubuntu 18.04 Command 'pyenv' not found, did you mean:") (using curl)
- Download FastAPI-OGBV folder from here - [OGBV/FastAPI - OGBV at main · tattle-made/OGBV](https://github.com/tattle-made/OGBV/tree/main/FastAPI%20-%20OGBV "OGBV/FastAPI - OGBV at main · tattle-made/OGBV") which contains the script and config files
- Navigate to the downloaded folder and&#x20;

### Installing pyenv and dependencies

```
pyenv install 3.8.2
pyenv local 3.8.2
pipenv install --dev
pipenv shell
```

### Downloading the model

```
chmod +x bin/download_model
bin/download_model
```

### Start the server

```
chmod +x bin/start_server
bin/start_server
```

### Test an input using test\_server

```
chmod +x bin/test_request
bin/test_request
```

<br>
